// <auto-generated />
using System;
using HomeBusinessAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBusinessAssistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssistantDbContext))]
    [Migration("20260901181413_AddOnboardingFoundation")]
    partial class AddOnboardingFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AgentConfigurations");

                    b.HasIndex("AgentId")
                        .IsUnique()
                        .HasDatabaseName("UX_AgentConfigurations_AgentId");

                    b.HasIndex("CurrentRevisionId");

                    b.ToTable("AgentConfigurations", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultConcurrencyPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutableRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresInteractiveUserSession")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportedCommandsJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsManualRun")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsScheduling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectoryRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AgentDefinitions");

                    b.HasIndex("Enabled", "Id")
                        .HasDatabaseName("IX_AgentDefinitions_Enabled_Id");

                    b.ToTable("AgentDefinitions", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentLeaseEntity", b =>
                {
                    b.Property<string>("LeaseName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcquiredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FencingToken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("LeaseName")
                        .HasName("PK_AgentLeases");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_AgentLeases_ExpiresAtUtc");

                    b.ToTable("AgentLeases", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<Guid>("ConfigurationRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutableHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunnerVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AgentRuns");

                    b.HasIndex("ConfigurationRevisionId");

                    b.HasIndex("OccurrenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_AgentRuns_OccurrenceId");

                    b.HasIndex("AgentId", "StartedAtUtc")
                        .HasDatabaseName("IX_AgentRuns_AgentId_StartedAtUtc");

                    b.HasIndex("Status", "LastHeartbeatAtUtc")
                        .HasDatabaseName("IX_AgentRuns_Status_LastHeartbeatAtUtc");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimestampUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AgentRunEvents");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_AgentRunEvents_RunId_Sequence");

                    b.HasIndex("RunId", "TimestampUtc")
                        .HasDatabaseName("IX_AgentRunEvents_RunId_TimestampUtc");

                    b.ToTable("AgentRunEvents", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimestampUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AgentRunMetrics");

                    b.HasIndex("RunId", "Name", "TimestampUtc")
                        .HasDatabaseName("IX_AgentRunMetrics_RunId_Name_TimestampUtc");

                    b.ToTable("AgentRunMetrics", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowDisabledAgent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MisfireGracePeriodSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MisfirePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PausedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PinnedConfigurationRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryPolicyJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WakePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AgentSchedules");

                    b.HasIndex("PinnedConfigurationRevisionId");

                    b.HasIndex("AgentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AgentSchedules_AgentId_Name");

                    b.HasIndex("IsEnabled", "PausedUntilUtc", "AgentId")
                        .HasDatabaseName("IX_AgentSchedules_Active_AgentId");

                    b.ToTable("AgentSchedules", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AttentionItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AttentionItems");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_AttentionItems_DedupeKey");

                    b.HasIndex("Status", "Severity", "LastObservedAtUtc")
                        .HasDatabaseName("IX_AttentionItems_Status_Severity_LastObservedAtUtc");

                    b.ToTable("AttentionItems", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimestampUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_AuditEvents");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditEvents_CorrelationId");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_AuditEvents_RunId");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_AuditEvents_TimestampUtc");

                    b.HasIndex("TargetType", "TargetId", "TimestampUtc")
                        .HasDatabaseName("IX_AuditEvents_Target_TimestampUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ConfigurationRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ConfigurationRevisions");

                    b.HasIndex("AgentId", "ConfigurationHash")
                        .IsUnique()
                        .HasDatabaseName("UX_ConfigurationRevisions_AgentId_Hash");

                    b.HasIndex("AgentId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ConfigurationRevisions_AgentId_RevisionNumber");

                    b.ToTable("ConfigurationRevisions", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.DailySummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodEndUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodStartUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_DailySummaries");

                    b.HasIndex("GeneratedAtUtc")
                        .HasDatabaseName("IX_DailySummaries_GeneratedAtUtc");

                    b.HasIndex("LocalDate", "TimeZoneId", "GenerationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_DailySummaries_Date_TimeZone_Generation");

                    b.ToTable("DailySummaries", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.LocalNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttentionItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotBeforeUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThrottleKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_LocalNotifications");

                    b.HasIndex("AttentionItemId");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalNotifications_DedupeKey");

                    b.HasIndex("Status", "NotBeforeUtc", "CreatedAtUtc")
                        .HasDatabaseName("IX_LocalNotifications_Status_NotBeforeUtc_CreatedAtUtc");

                    b.ToTable("LocalNotifications", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.OnboardingCheckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentScopeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_OnboardingChecks");

                    b.HasIndex("AgentId");

                    b.HasIndex("SessionId", "Status", "ObservedAtUtc")
                        .HasDatabaseName("IX_OnboardingChecks_Session_Status_ObservedAtUtc");

                    b.HasIndex("SessionId", "Scope", "CheckKey", "AgentScopeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_OnboardingChecks_LatestIdentity");

                    b.ToTable("OnboardingChecks", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.OnboardingSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AcknowledgedWarningCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveSlot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedStepCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeferredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitializationKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_OnboardingSessions");

                    b.HasIndex("ActiveSlot")
                        .IsUnique()
                        .HasDatabaseName("UX_OnboardingSessions_ActiveSlot")
                        .HasFilter("ActiveSlot IS NOT NULL");

                    b.HasIndex("InitializationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_OnboardingSessions_InitializationKey")
                        .HasFilter("InitializationKey IS NOT NULL");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_OnboardingSessions_Status_CreatedAtUtc");

                    b.ToTable("OnboardingSessions", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.RunArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_RunArtifacts");

                    b.HasIndex("AgentId");

                    b.HasIndex("DeleteAfterUtc")
                        .HasDatabaseName("IX_RunArtifacts_DeleteAfterUtc");

                    b.HasIndex("RunId", "CreatedAtUtc")
                        .HasDatabaseName("IX_RunArtifacts_RunId_CreatedAtUtc");

                    b.ToTable("RunArtifacts", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ScheduleOccurrenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DueAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("KeepDisplayOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepSystemAwake")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentOccurrenceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresWake")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminalMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminalReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ScheduleOccurrences");

                    b.HasIndex("ConfigurationRevisionId");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasDatabaseName("UX_ScheduleOccurrences_RunId")
                        .HasFilter("RunId IS NOT NULL");

                    b.HasIndex("AgentId", "Status")
                        .HasDatabaseName("IX_ScheduleOccurrences_AgentId_Status");

                    b.HasIndex("ParentOccurrenceId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ScheduleOccurrences_ParentOccurrenceId_AttemptNumber")
                        .HasFilter("ParentOccurrenceId IS NOT NULL");

                    b.HasIndex("ScheduleId", "DueAtUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_ScheduleOccurrences_ScheduleId_DueAtUtc")
                        .HasFilter("ScheduleId IS NOT NULL");

                    b.HasIndex("Status", "DueAtUtc")
                        .HasDatabaseName("IX_ScheduleOccurrences_Status_DueAtUtc");

                    b.HasIndex("RequiresWake", "Status", "DueAtUtc")
                        .HasDatabaseName("IX_ScheduleOccurrences_RequiresWake_Status_DueAtUtc");

                    b.HasIndex("ScheduleId", "Status", "DueAtUtc")
                        .HasDatabaseName("IX_ScheduleOccurrences_ScheduleId_Status_DueAtUtc");

                    b.ToTable("ScheduleOccurrences", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.SystemSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.HasKey("Key")
                        .HasName("PK_SystemSettings");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentConfigurationEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ConfigurationRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ConfigurationRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ScheduleOccurrenceEntity", null)
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEventEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunMetricEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentScheduleEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ConfigurationRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PinnedConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ConfigurationRevisionEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.LocalNotificationEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AttentionItemEntity", null)
                        .WithMany()
                        .HasForeignKey("AttentionItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.OnboardingCheckEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.OnboardingSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.RunArtifactEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentRunEntity", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ScheduleOccurrenceEntity", b =>
                {
                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ConfigurationRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.ScheduleOccurrenceEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeBusinessAssistant.Infrastructure.Persistence.Entities.AgentScheduleEntity", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
