// <auto-generated />
using System;
using FounderScout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FounderScout.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FounderScoutDbContext))]
    [Migration("20260830200319_InitialFounderScoutPersistence")]
    partial class InitialFounderScoutPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.BrowserAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedSegmentIdsJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrowserProfileRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAuthenticatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailedRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSuccessfulRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspendedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_BrowserAccounts");

                    b.HasIndex("Enabled", "SessionStatus", "Id")
                        .HasDatabaseName("IX_BrowserAccounts_Enabled_Status_Id");

                    b.ToTable("BrowserAccounts", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.CandidateActionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedEvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedInvitationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_CandidateActions");

                    b.HasIndex("CorrelationId", "Id")
                        .HasDatabaseName("IX_CandidateActions_Correlation_Id");

                    b.HasIndex("RelatedRunId", "Id")
                        .HasDatabaseName("IX_CandidateActions_RelatedRun_Id");

                    b.HasIndex("CandidateId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_CandidateActions_Candidate_Occurred_Id");

                    b.ToTable("CandidateActions", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActivityScore")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalysisAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisClaimExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisWorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalSourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSourceProfileKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSeenAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FounderQualityScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeaCommitmentStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InvitationPriority")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastActivityText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAnalysisErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LatestEvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLocation")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OurFitScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RiskPenalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_Candidates");

                    b.HasIndex("CurrentSnapshotId")
                        .HasDatabaseName("IX_Candidates_CurrentSnapshotId");

                    b.HasIndex("LatestEvaluationId")
                        .HasDatabaseName("IX_Candidates_LatestEvaluationId");

                    b.HasIndex("LastSeenAtUtc", "Id")
                        .HasDatabaseName("IX_Candidates_LastSeen_Id");

                    b.HasIndex("Status", "InvitationPriority", "Id")
                        .HasDatabaseName("IX_Candidates_Status_Priority_Id");

                    b.HasIndex("Status", "AnalysisClaimExpiresAtUtc", "InvitationPriority", "Id")
                        .HasDatabaseName("IX_Candidates_AnalysisQueue_Priority_Id");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.CandidateIdentityAliasEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStrong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedValueHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("SourceAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_CandidateIdentityAliases");

                    b.HasIndex("CandidateId", "AliasType", "NormalizedValueHash")
                        .IsUnique()
                        .HasDatabaseName("UX_CandidateIdentityAliases_Candidate_Type_Hash");

                    b.HasIndex("NormalizedValueHash", "IsStrong", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("UX_CandidateIdentityAliases_StrongActiveHash")
                        .HasFilter("IsStrong = 1 AND IsActive = 1");

                    b.ToTable("CandidateIdentityAliases", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.DiscoveryCheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DomainRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSourceProfileKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_DiscoveryCheckpoints");

                    b.HasIndex("SegmentId");

                    b.HasIndex("DomainRunId", "Id")
                        .HasDatabaseName("IX_DiscoveryCheckpoints_DomainRun_Id");

                    b.HasIndex("AccountId", "SegmentId", "CapturedAtUtc")
                        .HasDatabaseName("IX_DiscoveryCheckpoints_Account_Segment_Captured");

                    b.ToTable("DiscoveryCheckpoints", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.DiscoverySegmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveLowYieldRuns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("NewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PausedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ViewedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_DiscoverySegments");

                    b.HasIndex("AssignedAccountId");

                    b.HasIndex("Enabled", "PausedUntilUtc", "Priority", "Id")
                        .HasDatabaseName("IX_DiscoverySegments_Active_Priority_Id");

                    b.ToTable("DiscoverySegments", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.EvaluationCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Maximum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Score")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_EvaluationCategories");

                    b.HasIndex("EvaluationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_EvaluationCategories_Evaluation_Key");

                    b.ToTable("EvaluationCategories", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.EvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActivityScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatorDeploymentVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatorModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatorProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FounderQualityScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal>("InvitationPriority")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OurFitScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawProviderArtifactReference")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RiskPenalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScorecardVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredEvaluationJson")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_Evaluations");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("CandidateId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Evaluations_Candidate_Created");

                    b.HasIndex("CandidateId", "InputHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Evaluations_Candidate_InputHash");

                    b.HasIndex("Status", "RetryAfterUtc", "CreatedAtUtc")
                        .HasDatabaseName("IX_Evaluations_Status_RetryAfter_Created");

                    b.ToTable("Evaluations", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.EvaluationRiskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_EvaluationRisks");

                    b.HasIndex("EvaluationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_EvaluationRisks_Evaluation_Key");

                    b.ToTable("EvaluationRisks", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.InvitationDraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedDraft")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactsUsedJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDraft")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SimilarityFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Superseded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationErrorsJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_InvitationDrafts");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_InvitationDrafts_Status_Created");

                    b.HasIndex("CandidateId", "Superseded", "CreatedAtUtc")
                        .HasDatabaseName("IX_InvitationDrafts_Candidate_Active_Created");

                    b.ToTable("InvitationDrafts", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.ManualInvitationWindowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryQueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReserveQueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_ManualInvitationWindows");

                    b.HasIndex("StartAtUtc", "EndAtUtc")
                        .HasDatabaseName("IX_ManualInvitationWindows_Start_End");

                    b.ToTable("ManualInvitationWindows", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.ProfileSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalSourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExtractionCompleteness")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExtractionConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedProfileJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawArtifactRelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAdapterVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceProfileKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSegmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ProfileSnapshots");

                    b.HasIndex("CandidateId", "CapturedAtUtc")
                        .HasDatabaseName("IX_ProfileSnapshots_Candidate_Captured");

                    b.HasIndex("DeleteAfterUtc", "Id")
                        .HasDatabaseName("IX_ProfileSnapshots_DeleteAfter_Id");

                    b.HasIndex("CandidateId", "SourceProfileKey", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_ProfileSnapshots_Candidate_SourceKey_ContentHash");

                    b.ToTable("ProfileSnapshots", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.ReportExportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteAfterUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterSortHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_ReportExports");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_ReportExports_Created_Id");

                    b.HasIndex("DeleteAfterUtc", "Id")
                        .HasDatabaseName("IX_ReportExports_DeleteAfter_Id");

                    b.ToTable("ReportExports", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.ScreeningDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ScreeningDecisions");

                    b.HasIndex("CandidateId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ScreeningDecisions_Candidate_Created");

                    b.HasIndex("SnapshotId", "RulesetVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_ScreeningDecisions_Snapshot_Ruleset");

                    b.ToTable("ScreeningDecisions", (string)null);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.CandidateActionEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.CandidateIdentityAliasEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.DiscoveryCheckpointEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.BrowserAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.DiscoverySegmentEntity", null)
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.DiscoverySegmentEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.BrowserAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.EvaluationCategoryEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.EvaluationEntity", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.EvaluationEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.ProfileSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.EvaluationRiskEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.EvaluationEntity", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.InvitationDraftEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.EvaluationEntity", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.ProfileSnapshotEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FounderScout.Infrastructure.Persistence.Entities.ScreeningDecisionEntity", b =>
                {
                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.CandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FounderScout.Infrastructure.Persistence.Entities.ProfileSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
