<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\agents\WakeRemote\WakeRemote.Agent\WakeRemote.Agent.csproj" />
    <ProjectReference Include="..\..\src\HomeBusinessAssistant.AgentSdk\HomeBusinessAssistant.AgentSdk.csproj" />
  </ItemGroup>

</Project>
