<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\HomeBusinessAssistant.Windows\HomeBusinessAssistant.Windows.csproj" />
    <ProjectReference Include="..\WakeRemote.Application\WakeRemote.Application.csproj" />
  </ItemGroup>

</Project>
