<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\HomeBusinessAssistant.AgentSdk\HomeBusinessAssistant.AgentSdk.csproj" />
    <ProjectReference Include="..\..\..\src\HomeBusinessAssistant.Application\HomeBusinessAssistant.Application.csproj" />
  </ItemGroup>
</Project>
